### ISSUE TITLE
test in google colab

### ISSUE THREAD

**Issue by AnukritiSinghh** [Zhenye-Na/self-driving-vehicles-sim-with-ml#2]
Hey, thanks for this awesome explanation!
I don't have excess to powerful GPU, is it possible to use google colab for testing? can I run drive.py on it and see it running on the autonomous mode?

**Comment by Zhenye-Na** [comment]
`drive.py` does not requirement heavy GPU usage.

I am gonna close it for now. let me know if you still have questions.
