### ISSUE TITLE
why the car didn't move in autonomous mode (unity-smi)?

### ISSUE THREAD

**Issue by quliang93** [Zhenye-Na/self-driving-vehicles-sim-with-ml#3]
Thanks for your work! Good job!
After training the model, I test drive.py with the simulator in autonomous mode. But the car didn't move. I finally solved this problem, and here are some tips if you meet the same problem. (On windows)
1. Make sure that you have installed Unity correctly. Udacity self-driving simulator is build with unity, so you have to install it.
2. Socket version compatible!!!! here is what I use: 
    pip install Flask-SocketIO==4.3.1 
    pip install python-engineio==3.13.2 
    pip install python-socketio==4.6.0 

I run drive.py on windows, firstly, you run command: "python drive.py model.h5"; secondly, you open the Udacity simulator, and choose autonomous mode. If everything is ok, the car should move.

**Comment by Zhenye-Na** [comment]
Thank you for contribution!

I have added the intructions and steps to solve this problem [here](https://github.com/Zhenye-Na/e2e-learning-self-driving-cars#the-car-didnt-move-in-autonomous-mode-windows).
